Make <Button> handle icons the right way
marigold-ui/marigold pull request #1188
Opened 2021-07-21 13:15 UTC by ti10le

closes #297

2021-07-21 20:28 UTC, sebald approved these changes
Not sure about this PR 🤔

2021-07-21 20:28 UTC, sebald commented on packages/components/src/Button/Button.tsx
> +            {icon ? (
Why do we want to our default button to handle icons?

2021-07-21 20:28 UTC, sebald commented on packages/components/src/Button/Button.tsx
> +                <Box as="span" pl={size === 'large' ? 'xsmall' : 'xxsmall'}>
This is not good, since we don't know what values the theme uses for `xmsall` and so on. Could look weird.

2021-07-21 20:34 UTC, sebald requested changes
I don't understand why this is necessary. Do we want to specifically handle icons? Aren't icons just another inline element?

2021-07-22 07:34 UTC, ti10le commented
I thought because of the figma design: https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=428%3A0

Our button can't handle exactly this. But yes, maybe we dont have to show this like exactly in the figma design.

2021-07-22 11:11 UTC, sebald commented
Well I guess we should sometimes question our designers. I really don't see why we need to support non even paddings 😳

2021-07-23 13:36 UTC, ti10le commented
I will close this PR. Designers should check the icon buttons design.

2021-07-23 13:36 UTC, closed without merging