feat(docs): add controls and essentials
marigold-ui/marigold pull request #1218
Opened 2021-08-16 12:57 UTC by viktoria-schwarz

2021-08-19 07:50 UTC, ti10le requested changes

2021-08-19 07:50 UTC, ti10le commented on packages/components/src/Field/Field.stories.mdx
> +        type: 'boolean',
Prop error is type string at the moment and changing some props here has no effect.

2021-08-19 07:50 UTC, ti10le commented on packages/components/src/Select/Select.stories.mdx
> +        type: 'boolean',
string because of the error message

2021-08-19 07:51 UTC, ti10le commented
When you click show code in storybook you got <object object> if you used our <Text> component. Storybook doesnt have the import correctly.

2021-08-20 07:30 UTC, viktoria-schwarz commented
> When you click show code in storybook you got if you used our component. Storybook doesnt have the import correctly.

I think it happens each time a Polymorphic Component is used (storybook doesn't know early enough what to render, so it just outputs object object), but I would leave it for now and note it down for later

2021-08-20 07:37 UTC, ti10le approved these changes

2021-08-20 07:37 UTC, merged