refa: Message new styling
marigold-ui/marigold pull request #2043
Opened 2022-04-27 13:58 UTC by sarahgm

2022-04-27 17:58 UTC, sebald requested changes
Just one little thing!

2022-04-28 05:56 UTC, sarahgm commented on packages/components/src/Message/Message.tsx
> +        role="presentation"
mit Button meinst du den Box Container?

2022-05-02 11:37 UTC, sebald commented on packages/components/src/Message/Message.tsx
> +        role="presentation"
Jap sorry

2022-05-02 11:39 UTC, sebald approved these changes

2022-05-02 11:39 UTC, merged