Chore: add a table of contents to docs
marigold-ui/marigold pull request #2256
Opened 2022-08-04 12:27 UTC by sarahgm

closes #2254

2022-08-04 18:50 UTC, sebald requested changes
Works great but overlapps content 😟
![image](https://user-images.githubusercontent.com/985701/182930326-2d25b297-af10-4b07-a755-6c417f9e2afc.png)

2022-08-05 06:29 UTC, sarahgm commented on docs-next/src/mdx/components.tsx
> +        ...(child.props as any),
??

2022-08-08 16:20 UTC, sebald approved these changes

2022-08-09 10:24 UTC, sebald approved these changes

2022-08-09 10:28 UTC, merged