Toc intersection observer
marigold-ui/marigold pull request #2397
Opened 2022-09-06 09:17 UTC by benediktgrether

2022-09-06 11:29 UTC, sebald commented
@benediktgrether awesome job 🥳 I have one suggestion to make it even more awesome: if the user scrolled all the way down to the buttom, can we make sure the last section is always highlighted? (e.g. "if scroll === bottom of page -> select last item)

![Screen Shot 2022-09-06 at 13 27 09](https://user-images.githubusercontent.com/985701/188624773-836a5d1a-ca2e-4cb6-9697-fe4b2bdd0512.jpg)

2022-09-06 13:59 UTC, benediktgrether commented
@sebald can we have a look tomorrow on this task? Because i found two issues.

2022-09-08 10:55 UTC, sebald requested changes
I found a little thing 🙈 there is no section highlighted initially :D

2022-09-08 10:56 UTC, sebald commented on docs/src/components/Toc.tsx
> +        elements[elementsLenght - 2].style.fontWeight = '400';
Also: can we add a class or `[data-attribute]` and do the styling inside Toc!? :)

2022-09-14 06:33 UTC, sebald approved these changes

2022-09-14 06:41 UTC, merged