Aspect docs
marigold-ui/marigold pull request #2455
Opened 2022-09-14 09:49 UTC by benediktgrether

2022-09-15 18:16 UTC, sebald requested changes

2022-09-15 18:16 UTC, sebald commented on docs/src/pages/components/aspect.mdx
> +An Example too show the `ratio` prop with the type `widescreen`.
```suggestion
An Example that shows the `ratio` prop set to `"widescreen"`.
```

2022-09-15 18:16 UTC, sebald commented on docs/src/pages/components/aspect.mdx
> +This Example use a Iframe inside the Aspect Component. The `ratio` prop has the `landscape` type.
```suggestion
This Example use a Iframe inside the Aspect Component. The `ratio` prop is set to `"landscape"`.
```

2022-09-21 06:51 UTC, sarahgm approved these changes

2022-09-21 06:54 UTC, sarahgm approved these changes

2022-09-21 06:55 UTC, merged