docs: refactor inline docs
marigold-ui/marigold pull request #2480
Opened 2022-09-19 08:21 UTC by benediktgrether

2022-09-19 09:44 UTC, sarahgm commented on docs/src/pages/components/inline.mdx
> +The `<Inline>` is a responsive layout component. It's inline element with space between each element. This component uses the spaces from the given theme or a responsive string.
better: It's inlining elements [...] ?

2022-09-19 09:45 UTC, sarahgm commented on docs/src/pages/components/inline.mdx
>  ## Use cases
write this in the description as usecases.

2022-09-19 09:49 UTC, sarahgm commented on docs/src/pages/components/inline.mdx
> +- [Button](/components/button/)
better in the description above because we don`t want a  Use case section

2022-09-19 16:52 UTC, sebald requested changes
Maybe remove the part what components can be used within? Should be possible to put every component there.

2022-09-19 16:52 UTC, sebald commented on docs/src/pages/components/inline.mdx
> +The `<Inline>` is a responsive layout component. It's inlining element with space between each element. This component uses the spaces from the given theme or a responsive string. Within the componen
Is there a component you cant use? :)

2022-09-20 07:15 UTC, sebald approved these changes

2022-09-20 07:15 UTC, sebald approved these changes

2022-09-20 07:38 UTC, merged