feat: add side property to label
marigold-ui/marigold pull request #2576
Opened 2022-10-20 14:29 UTC by sarahgm

2022-10-20 16:36 UTC, sebald requested changes
The implementation looks great. Can we maybe change the API? What about extending the label prop? 

label = ReactNode | { content: ReactNode, side: ... }

2022-10-20 16:36 UTC, sebald commented on .changeset/metal-insects-decide.md
> +"@marigold/components": patch
Minor! Since this is a new feature ;)

2022-10-20 18:23 UTC, sarahgm commented on .changeset/metal-insects-decide.md
> +"@marigold/components": patch
done

2022-10-21 07:12 UTC, sarahgm commented
> 

How would it work with that? I don't understand

2022-10-21 09:17 UTC, sebald commented
> How would it work with that? I don't understand @sebald

@sarahgm 

1. Extend the `FieldBaseProps` interface, instead of `label?: ReactNode` you have something like `label?: ReactNode | { content: ReactNode, side: 'left' | 'right' | 'top' }`
2. Inside the component check the label prop. If it is a ReactNode, just it as label, otherwhise use `label.content` as label (you could also switch that and check if `label.content` exists)
3. Then you can set them like you already did :) 

Why might this be better? Because the props are always together:

```jsx
    <TextField
      label="Promo Code"
      description="You'll find your promo code on the back of your ticket."
      errorMessage="Your promo code is not valid! Please review your input."
      value={value}
      onChange={setValue}
      error={error}
      inputMode="numeric"
      pattern="[0-9]*"
      side="left"
    />
```

VS

```jsx
    <TextField
      label={ 
          content: "Promo Code", 
          side: "left" 
      }
      description="You'll find your promo code on the back of your ticket."
      errorMessage="Your promo code is not valid! Please review your input."
      value={value}
      onChange={setValue}
      error={error}
      inputMode="numeric"
      pattern="[0-9]*"
    />
 ```

2022-10-21 13:23 UTC, sarahgm commented
> 

@sebald  can we have a look together monday? i have tried something

2022-11-09 15:42 UTC, sarahgm commented
if I type it as string it works for FieldBase but not for the others, with ReactNode its a typescript problem but I don't know how to solve it.

2022-11-11 16:01 UTC, sebald requested changes
I think there are some old props in there 😃

2022-11-11 16:01 UTC, sebald commented on docs/src/pages/components/number-field.mdx
> +      property: 'side',
This prop does not exist anymore right? 😃

2022-11-12 09:06 UTC, sarahgm commented
> I think there are some old props in there 😃

sorry, not anymore 😬

2022-11-14 14:30 UTC, sebald approved these changes

2022-11-14 14:30 UTC, merged