Tailwind: dialog component
marigold-ui/marigold pull request #2982
Opened 2023-05-23 09:45 UTC by sarahgm

2023-05-25 07:17 UTC, sebald requested changes

2023-05-25 07:17 UTC, sebald commented on packages/components/src/Dialog/Dialog.stories.tsx
> +import { useState } from '@storybook/addons';
```suggestion
```

2023-05-25 07:17 UTC, sebald commented on packages/components/src/Dialog/Dialog.stories.tsx
> +import React from 'react';
```suggestion
import React, { useState } from 'react';
```

2023-05-25 07:17 UTC, sebald commented on packages/components/src/Dialog/Dialog.test.tsx
> +      <ThemeProvider theme={theme}>
use test utils `render`!

2023-05-25 19:32 UTC, sarahgm commented on packages/components/src/Dialog/Dialog.test.tsx
> +      <ThemeProvider theme={theme}>
ok ok

2023-05-26 07:06 UTC, sebald commented on packages/components/src/Dialog/Dialog.test.tsx
> +import { Theme, ThemeProvider } from '@marigold/system';
```suggestion
import { Theme } from '@marigold/system';
```

2023-05-26 07:06 UTC, sebald approved these changes

2023-05-26 07:07 UTC, merged