docs: added center docs and demo
marigold-ui/marigold pull request #3157
Opened 2023-07-19 08:14 UTC by sarahgm

2023-07-19 10:13 UTC, sebald requested changes

2023-07-19 10:13 UTC, sebald commented on docs/content/components/center/space-center.demo.tsx
> +    <div className="h-28 w-full border border-slate-300 bg-slate-200" />
they should not be full width, otherwhise you are not seeing them centered :D maybe 50% or somthing?

2023-07-21 07:27 UTC, OsamaAbdellateef approved these changes

2023-07-24 09:37 UTC, sebald approved these changes

2023-07-24 09:37 UTC, merged