docs: add provider docs
marigold-ui/marigold pull request #3214
Opened 2023-07-24 13:28 UTC by sarahgm

2023-07-24 17:54 UTC, sebald commented
@sarahgm hmmm. Weird error 🤔

2023-07-25 07:50 UTC, sebald requested changes

2023-07-25 07:50 UTC, sebald commented on docs/content/components/provider/provider.mdx
> +      property: 'selector',
there is no selector anymore :D

2023-07-25 08:33 UTC, sarahgm commented on docs/content/components/provider/provider.mdx
> +      property: 'selector',
it is

2023-07-25 08:34 UTC, sarahgm commented on docs/content/components/provider/provider.mdx
> +      property: 'selector',
should I remove the prop?

2023-07-25 11:13 UTC, OsamaAbdellateef approved these changes

2023-07-26 09:29 UTC, sebald approved these changes

2023-07-26 09:29 UTC, merged