RAC: `<Table>` as react aria component
marigold-ui/marigold pull request #3415
Opened 2023-10-17 12:43 UTC by sarahgm

2023-10-19 18:20 UTC, sebald commented on packages/components/src/Table/Table.stories.tsx
> +// https://react-spectrum.adobe.com/react-aria/Table.html#nested-columns
Is this the error?

`TypeError: Cannot read properties of undefined (reading 'key')`

2023-10-19 19:07 UTC, sarahgm commented on packages/components/src/Table/Table.stories.tsx
> +// https://react-spectrum.adobe.com/react-aria/Table.html#nested-columns
Yes but why... I have tried everywhere to set id and key :/

2023-10-19 19:07 UTC, sarahgm commented on packages/components/src/Table/Table.stories.tsx
> +// https://react-spectrum.adobe.com/react-aria/Table.html#nested-columns
I have it like in the example

2023-10-20 09:15 UTC, sebald commented on packages/components/src/Table/Table.stories.tsx
> +// https://react-spectrum.adobe.com/react-aria/Table.html#nested-columns
Might be a bug in RAC: https://github.com/adobe/react-spectrum/issues/5281

2023-12-08 08:51 UTC, sebald requested changes

2023-12-08 09:15 UTC, sarahgm commented on docs/content/components/collection/table/table-async.demo.tsx
> -        <Table.Column key="mass" allowsSorting>
What do you mean? @sebald

2023-12-08 10:46 UTC, sarahgm commented on docs/content/components/collection/table/table-async.demo.tsx
> -        <Table.Column key="mass" allowsSorting>
done

2023-12-10 19:25 UTC, sebald approved these changes

2023-12-10 19:25 UTC, merged