[DST-363]: Adding Guideline-Page of how to use `Multiselection`
marigold-ui/marigold pull request #3824
Opened 2024-03-13 12:40 UTC by OsamaAbdellateef

2024-03-18 09:57 UTC, OsamaAbdellateef commented
now test is fixed  @sebald

2024-03-18 09:58 UTC, sebald submitted a review, later dismissed

2024-03-18 19:30 UTC, sebald requested changes
@OsamaAbdellateef is this now the only PR to merge? 

E.g. this includes the recipe and guide?

2024-03-18 19:30 UTC, sebald commented on packages/components/src/TagGroup/Tag.tsx
> +{
I think this does not belong here? :D

2024-03-18 19:30 UTC, sebald commented on packages/components/src/index.ts
> +export * from './Multiselect';
Only a recipe, do not export as component.

2024-03-19 09:42 UTC, OsamaAbdellateef commented
> @OsamaAbdellateef is this now the only PR to merge?
> 
> E.g. this includes the recipe and guide?

Yeah it includes both @sebald

2024-03-19 10:10 UTC, sebald commented on packages/components/src/index.ts
> +export * from './Multiselect';
please remove the line :) we don't want to expose this yet!

2024-03-19 10:11 UTC, sebald commented on packages/components/src/index.ts
> +export * from './Multiselect';
```suggestion
```

2024-03-19 10:19 UTC, sebald submitted a review, later dismissed

2024-03-19 10:33 UTC, sebald approved these changes

2024-03-19 10:33 UTC, merged