[DST_573]: Dialog Sizes
marigold-ui/marigold pull request #4160
Opened 2024-09-10 09:17 UTC by OsamaAbdellateef

# Description

Please include a summary of the change and which issue is fixed when no corresponding ticket is available. Add additional informations the reviewers should know.

- [] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx)

# What should be tested?

## Are they some special informations required to test something?

# Reviewers:

Which persons should review this PR? Add person with @mentions

Examples:
@marigold-ui/developer
@marigold-ui/designer

2024-09-24 13:10 UTC, sarahgm requested changes

2024-09-24 13:10 UTC, sarahgm commented on themes/theme-b2b/src/components/Dialog.styles.ts
> +        size: {
why has only b2b theme different sizes?

2024-09-24 13:14 UTC, sarahgm commented
did you use `--visual-viewport-height` like written in the ticket? Just wondering :)

2024-09-24 13:46 UTC, OsamaAbdellateef commented
> did you use `--visual-viewport-height` like written in the ticket? Just wondering :)

Ah i didn't use it because when i inspected that specific element i noticed that it  inherited `--visual-viewport`  from its parent @sarahgm 
But you can re-check to make sure that it is working

2024-09-30 13:18 UTC, sarahgm commented
Ah I also noticed, this change require a UI kit update right? @OsamaAbdellateef

2024-10-01 13:06 UTC, sarahgm approved these changes

2024-10-02 07:15 UTC, merged