refa[DST-598]: improve range slider
marigold-ui/marigold pull request #4286
Opened 2024-11-07 07:02 UTC by aromko

# Description

The slider is completely refactored. I oriented myelf on https://react-spectrum.adobe.com/react-aria/Slider.html.

- the stories are updated, also added new stories
- add a visibile “indicator” for the selected track
- updated/added tests
- rewrite slider documentation according to our component pages

- [x] This change requires a UI-Kit update - inform Alex Tirado (@tirado-rx), Benji @benjirsvx 

# What should be tested?

- Storybook
- Documentation

# Reviewers:

@marigold-ui/developer
@tirado-rx or @benjirsvx

2024-11-08 07:38 UTC, aromko commented on themes/theme-core/src/components/Slider.styles.ts
> +  container: cva([
It's the workaround to make it work with Fieldgroup and their label.

2024-11-11 12:34 UTC, aromko commented on themes/theme-core/src/components/Slider.styles.ts
> +  container: cva([
@sebald ping

2024-11-12 10:43 UTC, sebald requested changes

2024-11-12 10:43 UTC, sebald commented on docs/content/components/form/slider/slider.mdx
> +Sliders allow users to view and select a value (or range) along a track. They’re ideal for adjusting settings such as volume and brightness.
```suggestion
Sliders allow users to view and select a value (or range) along a track. They’re ideal for adjusting settings such as volume and brightness.

```

2024-11-12 10:43 UTC, sebald commented on docs/content/components/form/slider/slider.mdx
> +A slider’s `step` size defines the increments at which the slider can move, allowing users to make finer or coarser adjustments based on the context—such as adjusting volume in single steps versus in
```suggestion
A slider’s `step` size defines the increments at which the slider can move, allowing users to make finer or coarser adjustments based on the context — such as adjusting volume in single steps versus increments of ten. Setting an appropriate step size enhances usability, especially for precise inputs. The `step` default increment is 1.
```

Added whitespace to `—` (AI is forgetting that all the time ;D) and moved the default sentence to the paragraph.

2024-11-12 10:43 UTC, sebald commented on docs/content/components/form/slider/slider.mdx
> +The `step` default increment is <strong>1</strong>.
```suggestion
```

2024-11-12 10:58 UTC, merged