DST-611: revise `<Scrollable>` component
marigold-ui/marigold pull request #4301
Opened 2024-11-15 10:20 UTC by aromko

# Description

Revise component according to our new template

# What should be tested?

- documentation
- Storybook

# Reviewers

@marigold-ui/developer
@marigold-ui/designer

2024-11-21 12:41 UTC, sarahgm requested changes

2024-11-25 11:14 UTC, sebald requested changes

2024-11-25 11:14 UTC, sebald commented on docs/content/components/layout/scrollable/scroll-horizontal.demo.tsx
> +        <Rectangle key={index} variant="primary" height="100px" width="200px" />
```suggestion
        <Rectangle key={index} height="100px" width="200px" />
```

2024-11-25 11:14 UTC, sebald commented on docs/content/components/layout/scrollable/scroll-vertical.demo.tsx
> +        <Rectangle key={index} variant="primary" height="100px" width="200px" />
```suggestion
        <Rectangle key={index} height="100px" width="200px" />
```

2024-11-25 11:14 UTC, sebald commented on docs/content/components/layout/scrollable/scroll-horizontal.demo.tsx
> +        <Rectangle key={index} variant="primary" height="100px" width="200px" />
removed primary :)

2024-11-25 13:39 UTC, sebald approved these changes

2024-11-25 13:39 UTC, merged