init marigold docs with gatsby
marigold-ui/marigold pull request #766
Opened 2021-02-08 14:22 UTC by ti10le

2021-02-08 21:46 UTC, sebald approved these changes
No need to have a complete "sub" project, add `docs` to the workspaces in the root `package.json` so everything is installed correctly.

Remove `gitignore`, prettier files

2021-02-08 21:49 UTC, sebald requested changes

2021-02-08 21:49 UTC, sebald commented on docs/gatsby-config.js
> +/**
Hm, plugins!? :)

E.g.

```
module.exports = {
  siteMetadata: {
    title: "The Code takes care of itself",
  },
  plugins: [
    "gatsby-plugin-sharp",
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-sitemap",
    "gatsby-plugin-offline",
    {
      resolve: "gatsby-plugin-manifest",
      options: {
        icon: "src/images/icon.png",
      },
    },
    "gatsby-plugin-mdx",
    "gatsby-transformer-sharp",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "images",
        path: "src/images/",
      },
      __key: "images",
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "pages",
        path: "src/pages/",
      },
      __key: "pages",
    },
  ],
};
```

2021-02-09 07:51 UTC, ti10le commented on docs/gatsby-config.js
> +/**
Ok dachte plugins nach und nach hinzufügen wenn man auch wirklich eins benutzt

2021-02-09 21:01 UTC, sebald commented on docs/gatsby-config.js
> +/**
@ti10le das sind praktisch die Standard Plugins für Gatsby. Wenn man `npm init gatsby` macht werden die einem vorgeschlagen :)

Bis auf das offline plugin brauchen wir davon ja alles. MDX, files als source.

2021-02-10 07:54 UTC, ti10le commented on docs/gatsby-config.js
> +/**
OK

2021-03-05 06:57 UTC, sebald commented
@ti10le @viktoria-schwarz is this superseded by the other PR?

2021-03-08 08:35 UTC, closed without merging